/**
 * CAT TOWN — the unlock graph (balance-and-meta.md §4).
 *
 * A small authored catalog plus an OPEN registry. Every entry is an addition
 * to the pool of possibilities — a cat who might come along, a stall that
 * might stock something, a drain that might be open — never a stat bump.
 *
 * The catalog is deliberately NOT a closed list: `registerUnlocks()` appends
 * defs at runtime, which is how Stands, items and events generated by the GM
 * or by other players become buyable here (§4 "the unlock IS the content
 * pool"). Every function in this layer takes an explicit `catalog` argument
 * (defaulting to the live registry) so the pure logic never depends on
 * module state.
 *
 * Pure: imports core/types only, no rng, no I/O.
 */
import type { PlaceDef, PlaceId, UnlockDef, UnlockId } from "./types.js";

/* ------------------------------------------------------------------ */
/* Places — the town as a map, not a list                             */
/* ------------------------------------------------------------------ */

/**
 * Marker anchors are design px on the 1280×720 backdrop, each sitting on the
 * thing it names in the painted `scene:catTown` art (the board on the wall,
 * the bowls on the ledge, the cart by the shelters, the drain mouth on the
 * right) — so the unlock list reads as somewhere you walk to, not a row in a
 * table. The lower band is left clear for the clowder and the action bar.
 */
export const PLACES: readonly PlaceDef[] = [
  {
    id: "board",
    name: "THE NOTICE BOARD",
    blurb: "what other cats pinned up",
    art: "town:board",
    glyph: "▤",
    x: 148,
    y: 300,
  },
  {
    id: "bowls",
    name: "THE BOWLS",
    blurb: "how many cats eat here",
    art: "town:bowls",
    glyph: "◡",
    x: 146,
    y: 452,
  },
  {
    id: "cart",
    name: "THE CART",
    blurb: "the Peddler's blanket",
    art: "town:cart",
    glyph: "⚖",
    x: 392,
    y: 452,
  },
  {
    id: "stoop",
    name: "THE STOOP",
    blurb: "who sleeps on it",
    art: "town:stoop",
    glyph: "⌂",
    x: 566,
    y: 436,
  },
  {
    id: "fence",
    name: "THE FENCE",
    blurb: "a raccoon's hoard",
    art: "town:fence",
    glyph: "※",
    x: 966,
    y: 424,
  },
  {
    id: "drain",
    name: "THE STORM DRAIN",
    blurb: "how far down it goes",
    art: "town:drain",
    glyph: "◍",
    x: 1148,
    y: 408,
  },
];

/** Unknown / pooled places fall back to the notice board. */
export const DEFAULT_PLACE: PlaceId = "board";

export function placeDef(id: PlaceId): PlaceDef {
  return (
    PLACES.find((p) => p.id === id) ??
    PLACES.find((p) => p.id === DEFAULT_PLACE)!
  );
}

/* ------------------------------------------------------------------ */
/* The authored catalog                                               */
/* ------------------------------------------------------------------ */

/**
 * Costs are tuned against `computePayout` (payout.ts): a losing floor-2 run
 * banks ~72, a clean victory ~757. The whole authored catalog is 2650 (see
 * tests/meta.spec.ts, which pins the number), so a player who never wins
 * still opens the first door in two runs and the town keeps something worth
 * wanting for a dozen more.
 */
export const BUILTIN_UNLOCKS: readonly UnlockDef[] = [
  /* ---- THE BOWLS — how many cats descend ----------------------------
   * A run fields two and recruits a third on its own (§2). The FOURTH
   * bowl is the only one the town has to buy. */
  {
    id: "slot:fourth",
    name: "A Fourth Bowl",
    pitch: "Room for one more: the old clowder, whole again, four deep.",
    cost: 320,
    requires: ["class:hexer"],
    place: "bowls",
  },

  /* ---- THE STOOP — who is available to come ------------------------- */
  {
    id: "class:hexer",
    name: "Mora's Corner",
    pitch: "Mora takes the dry corner; the Hexer can join a descent.",
    cost: 90,
    requires: [],
    place: "stoop",
  },
  {
    id: "class:medic",
    name: "Baguette's Basket",
    pitch: "A laundry basket by the pipes; the Medic can join a descent.",
    cost: 90,
    requires: [],
    place: "stoop",
  },
  {
    id: "pool:class",
    name: "The Stray Gate",
    pitch: "Cats other players dreamt up start turning up at the gate.",
    cost: 260,
    requires: ["class:hexer", "class:medic"],
    place: "stoop",
  },
  {
    id: "pool:stand",
    name: "The Shrine of Stands",
    pitch: "Stands from the shared pool bond to whoever walks past it.",
    cost: 240,
    requires: ["pool:class"],
    place: "stoop",
  },

  /* ---- THE FENCE — what you carry in -------------------------------- */
  {
    id: "gear:cardboardCuirass",
    name: "The Cardboard Cuirass",
    pitch: "The fence throws in corrugated armour before you go down.",
    cost: 140,
    requires: [],
    place: "fence",
  },
  {
    id: "shinies:tin",
    name: "A Fatter Tin",
    pitch: "Twenty more shinies rattling in the tin at the first step.",
    cost: 100,
    requires: [],
    place: "fence",
    grants: { shinies: 20 },
  },
  {
    id: "pool:item",
    name: "The Lost & Found",
    pitch: "Things from the shared pool start showing up in the loot.",
    cost: 220,
    requires: ["gear:cardboardCuirass"],
    place: "fence",
  },

  /* ---- THE CART — the Peddler --------------------------------------- */
  {
    id: "shop:bigBlanket",
    name: "A Bigger Blanket",
    pitch: "One more thing laid out on the blanket at every stall.",
    cost: 180,
    requires: [],
    place: "cart",
  },
  {
    id: "shop:reroll",
    name: "A Word With The Peddler",
    pitch: "Talk him into laying out a different lot, once per stall.",
    cost: 240,
    requires: ["shop:bigBlanket"],
    place: "cart",
  },

  /* ---- THE NOTICE BOARD — what can happen down there ---------------- */
  {
    id: "encounter:strayPatrol",
    name: "The Patrol Route",
    pitch: "Word gets around: new kinds of trouble start working the route.",
    cost: 150,
    requires: [],
    place: "board",
  },
  {
    id: "pool:event",
    name: "The Pinned Notices",
    pitch: "Events written by the GM and other cats get pinned up here.",
    cost: 220,
    requires: ["encounter:strayPatrol"],
    place: "board",
  },

  /* ---- THE STORM DRAIN — how far down ------------------------------- */
  {
    id: "biome:2",
    name: "The Storm Drain",
    pitch: "The grate comes loose: a second biome opens under the boiler.",
    cost: 400,
    requires: ["slot:fourth"],
    place: "drain",
    grants: { biome: 2 },
  },
];

/* ------------------------------------------------------------------ */
/* Registry — additive, for pooled/generated content                  */
/* ------------------------------------------------------------------ */

const registry = new Map<UnlockId, UnlockDef>(
  BUILTIN_UNLOCKS.map((d) => [d.id, d]),
);

/**
 * Append (or replace) unlock defs — how a generated Stand/item/event becomes
 * purchasable in town. Later registrations of the same id win; the built-ins
 * come back with `resetUnlockRegistry()`.
 */
export function registerUnlocks(defs: readonly UnlockDef[]): void {
  for (const def of defs) registry.set(def.id, def);
}

/** Drop everything registered at runtime (tests, run teardown). */
export function resetUnlockRegistry(): void {
  registry.clear();
  for (const d of BUILTIN_UNLOCKS) registry.set(d.id, d);
}

/** The live catalog, built-ins first then registrations, in insertion order. */
export function unlockCatalog(): readonly UnlockDef[] {
  return [...registry.values()];
}

export function unlockDef(
  id: UnlockId,
  catalog: readonly UnlockDef[] = unlockCatalog(),
): UnlockDef | null {
  return catalog.find((d) => d.id === id) ?? null;
}

/** The defs sold at a place, in catalog order. */
export function unlocksAt(
  place: PlaceId,
  catalog: readonly UnlockDef[] = unlockCatalog(),
): UnlockDef[] {
  const known = new Set(PLACES.map((p) => p.id));
  return catalog.filter((d) =>
    known.has(d.place) ? d.place === place : place === DEFAULT_PLACE,
  );
}

/** Σ of every price in the catalog — the town's total ask. */
export function catalogCost(
  catalog: readonly UnlockDef[] = unlockCatalog(),
): number {
  return catalog.reduce((s, d) => s + d.cost, 0);
}
